
function signup(){
  // here we will get the id of the document from html
  // first we will store it in an variable and we using const It means the variable reference cannot be reassigned
  const name = document.getElementById("name").value;
  // We use .value because user input in form fields is stored in the input’s value property, not as inner text.
  const email = document.getElementById("email").value;
  const password = document.getElementById("password").value;
//  here auth → Firebase Authentication instance.
// createUserWithEmailAndPassword(...) → Firebase method that:
// creates a new user account
// stores the user in Firebase Auth
// uses email and password for login.
// Returns a Promise.
  auth.createUserWithEmailAndPassword(email,password)
  // .then() runs after the user is successfully created.
// cred (credentials) is the result object returned by Firebase.
// cred.user contains the authenticated user info.
  .then(cred => {
// uid = unique user ID generated by Firebase.
// This ID:
// never changes
// is used to uniquely identify the user across your app
// is perfect for database documents.
// db → Firestore database instance.
// .collection('AuthProjectUsers') → references a collection named AuthProjectUsers.
// If it doesn’t exist, Firestore creates it automatically.
    return db.collection("AuthProjectUsers")
        // .doc(cred.user.uid)
// Creates (or references) a document
// Document ID = the user’s uid
// This links Auth user ↔ Firestore data (best practice).
    .doc(cred.user.uid)
// .set() → writes data to the document.
// Stores:
// name → user’s name
// email → user’s email
// isAdmin: false → role flag (non-admin by default)
    .set({
      name: name,
      email: email,
      isAdmin: false
    });
  })
        .then(() => {
          alert('Signup successful!');
          window.location.href = 'login.html';
        })
        .catch(err => alert(err.message));
    }
    const provider = new firebase.auth.GoogleAuthProvider();

function googleAuth() {
  auth.signInWithPopup(provider)
    .then(result => {
      const user = result.user;

      // Save user in Firestore (only if new)
      return db.collection("AuthProjectUsers")
        .doc(user.uid)
        .set({
          name: user.displayName,
          email: user.email,
          isAdmin: false,
          provider: "google"
        }, { merge: true });
    })
    .then(() => {
      window.location.href = "dashboard.html";
    })
    .catch(err => {
      alert(err.message);
    });
}
